#include "GameExceptions/InvalidCredentialsException.idl"
#include "GameExceptions/AlreadyLoggedInException.idl"
#include "GameExceptions/NotLoggedInException.idl"
#include "GameExceptions/UserExistenceException.idl"
#include "GameExceptions/InvalidRequestException.idl"
#include "GameExceptions/InvalidWordException.idl"
#include "GameExceptions/ObjectExistenceException.idl"
#include "GameExceptions/NoPlayersAvailableException.idl"
#include "Objects/GameDetails.idl"
#include "Objects/LeaderBoard.idl"
#include "Objects/Lobby.idl"
#include "Objects/Player.idl"
#include "Callback.idl"

module LEXIUser {

#include "Game.idl"

interface UserManagementInterface {

    void login(Callback callback)
    raises (InvalidCredentialsException, AlreadyLoggedInException, UserExistenceException);

    void logout()
    raises (NotLoggedInException);

    void changeUsername (in string username, in string newUsername)
    raises (InvalidRequestException,UserExistenceException, NotLoggedInException, ObjectExistenceException);

    void changePassword(in string username, in string newPassword)
    raises (InvalidRequestException,UserExistenceException, NotLoggedInException, ObjectExistenceException);

    void deleteProfile (in string username)
    raises(InvalidRequestException,NotLoggedInException,ObjectExistenceException)

    void startGame()
    raises (NoPlayersAvailableException, NotLoggedInException);


    void submitWord(in string word)
    raises (InvalidWordException, NotLoggedInException);

    void getGameResult()
    raises (NotLoggedInException);

    void getGameHistory()
    raises (NotLoggedInException, InvalidRequestException);

    sequence<LeaderBoard> getLeaderboard()
    raises (NotLoggedInException);

};

};
