#include "ProgramUtilities.idl"
#include "UIControllers.idl"
module org {
    module amalgam {
        module Service {
            module PlayerServiceModule {

                interface PlayerService {
                    typedef org::amalgam::UIControllers::PlayerCallback PlayerCallback;

                    void login(in PlayerCallback player_callback,in string password)
                        raises (org::amalgam::Utils::Exceptions::AlreadyLoggedInException, org::amalgam::Utils::Exceptions::InvalidCredentialsException, org::amalgam::Utils::Exceptions::UserExistenceException);

                    void logout(in string username)
                        raises (org::amalgam::Utils::Exceptions::NotLoggedInException);

                    void createAccount (in string username, in string password)
                        raises (org::amalgam::Utils::Exceptions::AccountCreationFailedException);

                    void changeUsername(in string username, in string newUsername)
                        raises (org::amalgam::Utils::Exceptions::ChangeUsernameFailedException);

                    void changePassword(in string username, in string newPassword)
                        raises (org::amalgam::Utils::Exceptions::ChangePasswordFailedException);

                    void accountDeletionRequest(in string username)
                        raises (org::amalgam::Utils::Exceptions::DeleteAccountFailedException);

                    string getGameHistory(in string username)
                        raises (org::amalgam::Utils::Exceptions::GameHistoryUnavailableException, org::amalgam::Utils::Exceptions::InGameException);
                };
            };
                    };
    };
};

