package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/PlayerCallbackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Thursday, May 16, 2024 1:07:10 AM PST
*/

abstract public class PlayerCallbackHelper
{
  private static String  _id = "IDL:org/amalgam/UIControllers/PlayerCallback:1.0";

  public static void insert (org.omg.CORBA.Any a, org.amalgam.UIControllers.PlayerCallback that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.amalgam.UIControllers.PlayerCallback extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.amalgam.UIControllers.PlayerCallbackHelper.id (), "PlayerCallback");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.amalgam.UIControllers.PlayerCallback read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PlayerCallbackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.amalgam.UIControllers.PlayerCallback value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.amalgam.UIControllers.PlayerCallback narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.amalgam.UIControllers.PlayerCallback)
      return (org.amalgam.UIControllers.PlayerCallback)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.amalgam.UIControllers._PlayerCallbackStub stub = new org.amalgam.UIControllers._PlayerCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.amalgam.UIControllers.PlayerCallback unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.amalgam.UIControllers.PlayerCallback)
      return (org.amalgam.UIControllers.PlayerCallback)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.amalgam.UIControllers._PlayerCallbackStub stub = new org.amalgam.UIControllers._PlayerCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
