package org.amalgam.UIControllers;

/**
* org/amalgam/UIControllers/PlayerCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Thursday, May 16, 2024 1:07:10 AM PST
*/

public final class PlayerCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.UIControllers.PlayerCallback value = null;

  public PlayerCallbackHolder ()
  {
  }

  public PlayerCallbackHolder (org.amalgam.UIControllers.PlayerCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.UIControllers.PlayerCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.UIControllers.PlayerCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.UIControllers.PlayerCallbackHelper.type ();
  }

}
