package org.amalgam.Service.PlayerServiceModule;


/**
* org/amalgam/Service/PlayerServiceModule/PlayerCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public abstract class PlayerCallbackPOA extends org.omg.PortableServer.Servant
 implements PlayerCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("uiCall", new Integer (0));
    _methods.put ("setUser", new Integer (1));
    _methods.put ("getPlayer", new Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/amalgam/Service/PlayerServiceModule/PlayerCallback/uiCall
       {
         try {
           this.uiCall ();
           out = $rh.createReply();
         } catch (org.amalgam.Service.PlayerExceptions.InvalidRequest $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // org/amalgam/Service/PlayerServiceModule/PlayerCallback/setUser
       {
         try {
           org.amalgam.Utils.Objects.Player player = org.amalgam.Service.PlayerServiceModule.PlayerServicePackage.PlayerHelper.read (in);
           this.setUser (player);
           out = $rh.createReply();
         } catch (org.amalgam.Service.PlayerExceptions.InvalidRequest $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // org/amalgam/Service/PlayerServiceModule/PlayerCallback/getPlayer
       {
         try {
           org.amalgam.Utils.Objects.Player $result = null;
           $result = this.getPlayer ();
           out = $rh.createReply();
           org.amalgam.Utils.Objects.PlayerHelper.write (out, $result);
         } catch (org.amalgam.Service.PlayerExceptions.InvalidRequest $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/Service/PlayerServiceModule/PlayerCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerCallback _this() 
  {
    return PlayerCallbackHelper.narrow(
    super._this_object());
  }

  public PlayerCallback _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerCallbackPOA
