package org.amalgam.Service.Game.GameServicePackage;

/**
* org/amalgam/Service/Game/GameServicePackage/GameRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class GameRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.Game.GameServicePackage.GameRoom value = null;

  public GameRoomHolder ()
  {
  }

  public GameRoomHolder (org.amalgam.Service.Game.GameServicePackage.GameRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.Game.GameServicePackage.GameRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.Game.GameServicePackage.GameRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.Game.GameServicePackage.GameRoomHelper.type ();
  }

}
