package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/GameDetail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class GameDetail implements org.omg.CORBA.portable.IDLEntity
{
  public int playerID = (int)0;
  public int lobbyID = (int)0;
  public int totalPoints = (int)0;

  public GameDetail ()
  {
  } // ctor

  public GameDetail (int _playerID, int _lobbyID, int _totalPoints)
  {
    playerID = _playerID;
    lobbyID = _lobbyID;
    totalPoints = _totalPoints;
  } // ctor

} // class GameDetail
