package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/GameRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class GameRoom implements org.omg.CORBA.portable.IDLEntity
{
  public int roomID = (int)0;
  public String players[] = null;

  public GameRoom ()
  {
  } // ctor

  public GameRoom (int _roomID, String[] _players)
  {
    roomID = _roomID;
    players = _players;
  } // ctor

} // class GameRoom
