package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/Lobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class Lobby implements org.omg.CORBA.portable.IDLEntity
{
  public int lobbyId = (int)0;
  public String created_by = null;
  public String winner = null;

  public Lobby ()
  {
  } // ctor

  public Lobby (int _lobbyId, String _created_by, String _winner)
  {
    lobbyId = _lobbyId;
    created_by = _created_by;
    winner = _winner;
  } // ctor

} // class Lobby
