package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public String password = null;
  public String lastLogin = null;

  public Player ()
  {
  } // ctor

  public Player (int _id, String _name, String _password, String _lastLogin)
  {
    id = _id;
    name = _name;
    password = _password;
    lastLogin = _lastLogin;
  } // ctor

} // class Player
