# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.Service.PlayerServiceModule generated by omniidl

import omniORB
omniORB.updateModule("org.amalgam.Service.PlayerServiceModule")

# ** 1. Stub files contributing to this module
import PlayerService_idl

# ** 2. Sub-modules

# ** 3. End
