package org.amalgam.lexilogicserver.DAL.SQLExceptions;

/**
* org/amalgam/lexilogicserver/DAL/SQLExceptions/SQLCreateErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class SQLCreateErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateError value = null;

  public SQLCreateErrorHolder ()
  {
  }

  public SQLCreateErrorHolder (org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateErrorHelper.type ();
  }

}
