package org.amalgam.lexilogicserver.DAL.SQLExceptions;

/**
* org/amalgam/lexilogicserver/DAL/SQLExceptions/SQLUpdateErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class SQLUpdateErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLUpdateError value = null;

  public SQLUpdateErrorHolder ()
  {
  }

  public SQLUpdateErrorHolder (org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLUpdateError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLUpdateErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLUpdateErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLUpdateErrorHelper.type ();
  }

}
