package org.amalgam.lexilogicserver.DAL.SQLExceptions;


/**
* org/amalgam/lexilogicserver/DAL/SQLExceptions/SQLUpdateError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class SQLUpdateError extends org.omg.CORBA.UserException
{
  public String reason = null;

  public SQLUpdateError ()
  {
    super(SQLUpdateErrorHelper.id());
  } // ctor

  public SQLUpdateError (String _reason)
  {
    super(SQLUpdateErrorHelper.id());
    reason = _reason;
  } // ctor


  public SQLUpdateError (String $reason, String _reason)
  {
    super(SQLUpdateErrorHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class SQLUpdateError
