package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/DuplicateWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class DuplicateWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DuplicateWordException value = null;

  public DuplicateWordExceptionHolder ()
  {
  }

  public DuplicateWordExceptionHolder (DuplicateWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DuplicateWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DuplicateWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DuplicateWordExceptionHelper.type ();
  }

}
