package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/InsufficientWordPointsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class InsufficientWordPointsHolder implements org.omg.CORBA.portable.Streamable
{
  public InsufficientWordPoints value = null;

  public InsufficientWordPointsHolder ()
  {
  }

  public InsufficientWordPointsHolder (InsufficientWordPoints initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InsufficientWordPointsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InsufficientWordPointsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InsufficientWordPointsHelper.type ();
  }

}
