package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/InvalidRoomIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class InvalidRoomIDHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidRoomID value = null;

  public InvalidRoomIDHolder ()
  {
  }

  public InvalidRoomIDHolder (InvalidRoomID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidRoomIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidRoomIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidRoomIDHelper.type ();
  }

}
