package org.amalgam.Service.GameExceptions;


/**
* org/amalgam/Service/GameExceptions/InvalidTotalPoints.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class InvalidTotalPoints extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidTotalPoints ()
  {
    super(InvalidTotalPointsHelper.id());
  } // ctor

  public InvalidTotalPoints (String _reason)
  {
    super(InvalidTotalPointsHelper.id());
    reason = _reason;
  } // ctor


  public InvalidTotalPoints (String $reason, String _reason)
  {
    super(InvalidTotalPointsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidTotalPoints
