package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/LobbyDoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class LobbyDoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public LobbyDoesNotExist value = null;

  public LobbyDoesNotExistHolder ()
  {
  }

  public LobbyDoesNotExistHolder (LobbyDoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LobbyDoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LobbyDoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LobbyDoesNotExistHelper.type ();
  }

}
