package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/WinnerDoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class WinnerDoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public WinnerDoesNotExist value = null;

  public WinnerDoesNotExistHolder ()
  {
  }

  public WinnerDoesNotExistHolder (WinnerDoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WinnerDoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WinnerDoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WinnerDoesNotExistHelper.type ();
  }

}
