package org.amalgam.Service.GameExceptions;


/**
* org/amalgam/Service/GameExceptions/WordFetchException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public final class WordFetchException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public WordFetchException ()
  {
    super(WordFetchExceptionHelper.id());
  } // ctor

  public WordFetchException (String _reason)
  {
    super(WordFetchExceptionHelper.id());
    reason = _reason;
  } // ctor


  public WordFetchException (String $reason, String _reason)
  {
    super(WordFetchExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class WordFetchException
