package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:34:02 PM SGT
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor

  public InvalidCredentials (String _message)
  {
    super(InvalidCredentialsHelper.id());
    message = _message;
  } // ctor


  public InvalidCredentials (String $reason, String _message)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidCredentials
