package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/NotLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:34:02 PM SGT
*/

public final class NotLoggedIn extends org.omg.CORBA.UserException
{
  public String message = null;

  public NotLoggedIn ()
  {
    super(NotLoggedInHelper.id());
  } // ctor

  public NotLoggedIn (String _message)
  {
    super(NotLoggedInHelper.id());
    message = _message;
  } // ctor


  public NotLoggedIn (String $reason, String _message)
  {
    super(NotLoggedInHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NotLoggedIn
