package org.amalgam.Utils.Exceptions;

/**
* org/amalgam/Utils/Exceptions/InvalidRequestExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 12:45:43 AM SGT
*/

public final class InvalidRequestExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidRequestException value = null;

  public InvalidRequestExceptionHolder ()
  {
  }

  public InvalidRequestExceptionHolder (InvalidRequestException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidRequestExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidRequestExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidRequestExceptionHelper.type ();
  }

}
