package org.amalgam.DAL.DALLeaderBoard;

/**
* org/amalgam/DAL/DALLeaderBoard/LeaderboardDALHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public final class LeaderboardDALHolder implements org.omg.CORBA.portable.Streamable
{
  public LeaderboardDAL value = null;

  public LeaderboardDALHolder ()
  {
  }

  public LeaderboardDALHolder (LeaderboardDAL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LeaderboardDALHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LeaderboardDALHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LeaderboardDALHelper.type ();
  }

}
