package org.amalgam.lexilogicserver.DAL.DALGameDetail;


/**
* org/amalgam/lexilogicserver/DAL/DALGameDetail/GameDetailsDALOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public interface GameDetailsDALOperations 
{
  void insertNewGameDetail (int playerID, int lobbyID, int totalPoints) throws org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLCreateError;
  org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDALPackage.GameDetail getGameDetailByID (int lobbyID) throws org.amalgam.lexilogicserver.DAL.SQLExceptions.SQLRetrieveError;
} // interface GameDetailsDALOperations
