package org.amalgam.lexilogicserver.DAL.DALGameDetail;

/**
* org/amalgam/lexilogicserver/DAL/DALGameDetail/GameDetailsDALHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class GameDetailsDALHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDAL value = null;

  public GameDetailsDALHolder ()
  {
  }

  public GameDetailsDALHolder (org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDAL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDALHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDALHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.lexilogicserver.DAL.DALGameDetail.GameDetailsDALHelper.type ();
  }

}
