package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/ControllerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Monday, May 13, 2024 11:20:51 PM SGT
*/

abstract public class ControllerInterfaceHelper
{
  private static String  _id = "IDL:org/amalgam/UIControllers/ControllerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ControllerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ControllerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ControllerInterfaceHelper.id (), "ControllerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ControllerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ControllerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ControllerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ControllerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ControllerInterface)
      return (ControllerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ControllerInterfaceStub stub = new _ControllerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ControllerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ControllerInterface)
      return (ControllerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ControllerInterfaceStub stub = new _ControllerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
