package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/ControllerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Thursday, May 9, 2024 1:16:39 PM SGT
*/

public interface ControllerInterface extends ControllerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControllerInterface
