package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/ControllerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Thursday, May 9, 2024 1:16:39 PM SGT
*/

public interface ControllerInterfaceOperations 
{
  void setObjectsUser (String objects) throws org.amalgam.ControllerException.InvalidRequestException;
  void fetchAndUpdate (String jsonString, String dataType) throws org.amalgam.ControllerException.InvalidRequestException;
} // interface ControllerInterfaceOperations
