package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/MatchmakeCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Sunday, June 30, 2024 9:50:09 PM SGT
*/

public interface MatchmakeCallbackOperations 
{
  String username ();
  void username (String newUsername);
  void joiningCall (String jsonString) throws org.amalgam.ControllerException.InvalidRequestException;
} // interface MatchmakeCallbackOperations
