package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/PlayerCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Sunday, June 30, 2024 9:50:09 PM SGT
*/

public interface PlayerCallback extends PlayerCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallback
