package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/PlayerCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Monday, July 1, 2024 10:33:09 PM SGT
*/

public interface PlayerCallbackOperations 
{
  String username ();
  void username (String newUsername);
  void uiCall (String jsonString) throws org.amalgam.ControllerException.InvalidRequestException;
} // interface PlayerCallbackOperations
