package org.amalgam.Utils.UIControllers;


/**
* org/amalgam/Utils/UIControllers/PlayerCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 12:45:43 AM SGT
*/

public interface PlayerCallback extends PlayerCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallback
