package org.amalgam.DAL.SQLExceptions;


/**
* org/amalgam/DAL/SQLExceptions/SQLUpdateError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public final class SQLUpdateError extends org.omg.CORBA.UserException
{
  public String reason = null;

  public SQLUpdateError ()
  {
    super(SQLUpdateErrorHelper.id());
  } // ctor

  public SQLUpdateError (String _reason)
  {
    super(SQLUpdateErrorHelper.id());
    reason = _reason;
  } // ctor


  public SQLUpdateError (String $reason, String _reason)
  {
    super(SQLUpdateErrorHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class SQLUpdateError
