package org.amalgam.Utils.ObjectExceptions;

/**
* org/amalgam/Utils/ObjectExceptions/CreatedByRetrievalExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public final class CreatedByRetrievalExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CreatedByRetrievalException value = null;

  public CreatedByRetrievalExceptionHolder ()
  {
  }

  public CreatedByRetrievalExceptionHolder (CreatedByRetrievalException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CreatedByRetrievalExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CreatedByRetrievalExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CreatedByRetrievalExceptionHelper.type ();
  }

}
