package org.amalgam.Utils.ObjectExceptions;

/**
* org/amalgam/Utils/ObjectExceptions/PlayerListRetrievalExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public final class PlayerListRetrievalExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerListRetrievalException value = null;

  public PlayerListRetrievalExceptionHolder ()
  {
  }

  public PlayerListRetrievalExceptionHolder (PlayerListRetrievalException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerListRetrievalExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerListRetrievalExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerListRetrievalExceptionHelper.type ();
  }

}
