package org.amalgam.Utils.ObjectExceptions;


/**
* org/amalgam/Utils/ObjectExceptions/PlayerListRetrievalException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public final class PlayerListRetrievalException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public PlayerListRetrievalException ()
  {
    super(PlayerListRetrievalExceptionHelper.id());
  } // ctor

  public PlayerListRetrievalException (String _reason)
  {
    super(PlayerListRetrievalExceptionHelper.id());
    reason = _reason;
  } // ctor


  public PlayerListRetrievalException (String $reason, String _reason)
  {
    super(PlayerListRetrievalExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class PlayerListRetrievalException
