package org.amalgam.Utils.ObjectExceptions;


/**
* org/amalgam/Utils/ObjectExceptions/SQLError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public final class SQLError extends org.omg.CORBA.UserException
{
  public String reason = null;

  public SQLError ()
  {
    super(SQLErrorHelper.id());
  } // ctor

  public SQLError (String _reason)
  {
    super(SQLErrorHelper.id());
    reason = _reason;
  } // ctor


  public SQLError (String $reason, String _reason)
  {
    super(SQLErrorHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class SQLError
