package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameRoomPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

public abstract class GameRoomPOA extends org.omg.PortableServer.Servant
 implements GameRoomOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_roomID", new Integer (0));
    _methods.put ("_set_roomID", new Integer (1));
    _methods.put ("_get_players", new Integer (2));
    _methods.put ("_set_players", new Integer (3));
    _methods.put ("addPlayer", new Integer (4));
    _methods.put ("getRoomID", new Integer (5));
    _methods.put ("getPlayers", new Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/amalgam/Utils/Objects/GameRoom/_get_roomID
       {
         int $result = (int)0;
         $result = this.roomID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // org/amalgam/Utils/Objects/GameRoom/_set_roomID
       {
         int newRoomID = in.read_long ();
         this.roomID (newRoomID);
         out = $rh.createReply();
         break;
       }

       case 2:  // org/amalgam/Utils/Objects/GameRoom/_get_players
       {
         String $result[] = null;
         $result = this.players ();
         out = $rh.createReply();
         org.amalgam.Utils.Objects.GameRoomPackage.PlayersListHelper.write (out, $result);
         break;
       }

       case 3:  // org/amalgam/Utils/Objects/GameRoom/_set_players
       {
         String newPlayers[] = org.amalgam.Utils.Objects.GameRoomPackage.PlayersListHelper.read (in);
         this.players (newPlayers);
         out = $rh.createReply();
         break;
       }

       case 4:  // org/amalgam/Utils/Objects/GameRoom/addPlayer
       {
         try {
           String playerName = in.read_string ();
           this.addPlayer (playerName);
           out = $rh.createReply();
         } catch (org.amalgam.Utils.ObjectExceptions.PlayerAlreadyInRoom $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.ObjectExceptions.PlayerAlreadyInRoomHelper.write (out, $ex);
         } catch (org.amalgam.Utils.ObjectExceptions.SQLError $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.ObjectExceptions.SQLErrorHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // org/amalgam/Utils/Objects/GameRoom/getRoomID
       {
         try {
           int $result = (int)0;
           $result = this.getRoomID ();
           out = $rh.createReply();
           out.write_long ($result);
         } catch (org.amalgam.Utils.ObjectExceptions.RoomDoesNotExistException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.ObjectExceptions.RoomDoesNotExistExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // org/amalgam/Utils/Objects/GameRoom/getPlayers
       {
         try {
           String $result[] = null;
           $result = this.getPlayers ();
           out = $rh.createReply();
           org.amalgam.Utils.Objects.GameRoomPackage.listHelper.write (out, $result);
         } catch (org.amalgam.Utils.ObjectExceptions.PlayerListRetrievalException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.ObjectExceptions.PlayerListRetrievalExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/Utils/Objects/GameRoom:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameRoom _this() 
  {
    return GameRoomHelper.narrow(
    super._this_object());
  }

  public GameRoom _this(org.omg.CORBA.ORB orb) 
  {
    return GameRoomHelper.narrow(
    super._this_object(orb));
  }


} // class GameRoomPOA
