package org.amalgam.Utils.Objects;

/**
* org/amalgam/Utils/Objects/GameDetailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

public final class GameDetailHolder implements org.omg.CORBA.portable.Streamable
{
  public GameDetail value = null;

  public GameDetailHolder ()
  {
  }

  public GameDetailHolder (GameDetail initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameDetailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameDetailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameDetailHelper.type ();
  }

}
