package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameRoomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

abstract public class GameRoomHelper
{
  private static String  _id = "IDL:org/amalgam/Utils/Objects/GameRoom:1.0";

  public static void insert (org.omg.CORBA.Any a, GameRoom that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameRoom extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameRoomHelper.id (), "GameRoom");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameRoom read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameRoomStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameRoom value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameRoom narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameRoom)
      return (GameRoom)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameRoomStub stub = new _GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameRoom unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameRoom)
      return (GameRoom)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameRoomStub stub = new _GameRoomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
