package org.amalgam.Utils.Objects;

/**
* org/amalgam/Utils/Objects/GameRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

public final class GameRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public GameRoom value = null;

  public GameRoomHolder ()
  {
  }

  public GameRoomHolder (GameRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameRoomHelper.type ();
  }

}
