package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/Lobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

public interface Lobby extends LobbyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Lobby
