package org.amalgam.Utils.Exceptions;


/**
* org/amalgam/Utils/Exceptions/CloseLobbyException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Thursday, May 9, 2024 1:16:39 PM SGT
*/

public final class CloseLobbyException extends org.omg.CORBA.UserException
{
  public String message = null;

  public CloseLobbyException ()
  {
    super(CloseLobbyExceptionHelper.id());
  } // ctor

  public CloseLobbyException (String _message)
  {
    super(CloseLobbyExceptionHelper.id());
    message = _message;
  } // ctor


  public CloseLobbyException (String $reason, String _message)
  {
    super(CloseLobbyExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class CloseLobbyException
