package org.amalgam.Utils.Exceptions;


/**
* org/amalgam/Utils/Exceptions/InvalidLobbyDataException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 29, 2024 9:39:27 PM PST
*/

public final class InvalidLobbyDataException extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidLobbyDataException ()
  {
    super(InvalidLobbyDataExceptionHelper.id());
  } // ctor

  public InvalidLobbyDataException (String _message)
  {
    super(InvalidLobbyDataExceptionHelper.id());
    message = _message;
  } // ctor


  public InvalidLobbyDataException (String $reason, String _message)
  {
    super(InvalidLobbyDataExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidLobbyDataException
