package org.amalgam.Utils.Exceptions;

/**
* org/amalgam/Utils/Exceptions/SQLErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Monday, May 20, 2024 3:00:32 PM PST
*/

public final class SQLErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public SQLError value = null;

  public SQLErrorHolder ()
  {
  }

  public SQLErrorHolder (SQLError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SQLErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SQLErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SQLErrorHelper.type ();
  }

}
