package org.amalgam.Utils.Exceptions;


/**
* org/amalgam/Utils/Exceptions/UserExistenceException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Monday, May 13, 2024 11:20:50 PM SGT
*/

public final class UserExistenceException extends org.omg.CORBA.UserException
{
  public String message = null;

  public UserExistenceException ()
  {
    super(UserExistenceExceptionHelper.id());
  } // ctor

  public UserExistenceException (String _message)
  {
    super(UserExistenceExceptionHelper.id());
    message = _message;
  } // ctor


  public UserExistenceException (String $reason, String _message)
  {
    super(UserExistenceExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UserExistenceException
