package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/DuplicateWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:34:25 PM SGT
*/

public final class DuplicateWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameExceptions.DuplicateWordException value = null;

  public DuplicateWordExceptionHolder ()
  {
  }

  public DuplicateWordExceptionHolder (org.amalgam.Service.GameExceptions.DuplicateWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameExceptions.DuplicateWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameExceptions.DuplicateWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameExceptions.DuplicateWordExceptionHelper.type ();
  }

}
