package org.amalgam.Service.GameExceptions;


/**
* org/amalgam/Service/GameExceptions/LobbyDoesNotExist.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:29:37 PM SGT
*/

public final class LobbyDoesNotExist extends org.omg.CORBA.UserException
{
  public String reason = null;

  public LobbyDoesNotExist ()
  {
    super(LobbyDoesNotExistHelper.id());
  } // ctor

  public LobbyDoesNotExist (String _reason)
  {
    super(LobbyDoesNotExistHelper.id());
    reason = _reason;
  } // ctor


  public LobbyDoesNotExist (String $reason, String _reason)
  {
    super(LobbyDoesNotExistHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class LobbyDoesNotExist
