package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/WinnerDoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:34:25 PM SGT
*/

public final class WinnerDoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameExceptions.WinnerDoesNotExist value = null;

  public WinnerDoesNotExistHolder ()
  {
  }

  public WinnerDoesNotExistHolder (org.amalgam.Service.GameExceptions.WinnerDoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameExceptions.WinnerDoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameExceptions.WinnerDoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameExceptions.WinnerDoesNotExistHelper.type ();
  }

}
