package org.amalgam.Service.GameServiceModule;


/**
* org/amalgam/Service/GameServiceModule/GameServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:29:37 PM SGT
*/

public abstract class GameServicePOA extends org.omg.PortableServer.Servant
 implements GameServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fetchWordBox", new Integer (0));
    _methods.put ("getLeaderboards", new Integer (1));
    _methods.put ("verifyWord", new Integer (2));
    _methods.put ("validateTotalPoints", new Integer (3));
    _methods.put ("fetchWinner", new Integer (4));
    _methods.put ("insertLobby", new Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/amalgam/Service/GameServiceModule/GameService/fetchWordBox
       {
         try {
           int roomID = in.read_long ();
           char $result[][] = null;
           $result = this.fetchWordBox (roomID);
           out = $rh.createReply();
           org.amalgam.Service.GameServiceModule.GameServicePackage.MatrixHelper.write (out, $result);
         } catch (org.amalgam.Service.GameExceptions.WordFetchException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.WordFetchExceptionHelper.write (out, $ex);
         } catch (org.amalgam.Service.GameExceptions.InvalidRoomID $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.InvalidRoomIDHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // org/amalgam/Service/GameServiceModule/GameService/getLeaderboards
       {
         try {
           org.amalgam.Utils.Objects.Leaderboard $result[] = null;
           $result = this.getLeaderboards ();
           out = $rh.createReply();
           org.amalgam.Service.GameServiceModule.GameServicePackage.leaderboardsHelper.write (out, $result);
         } catch (org.amalgam.Service.GameExceptions.EmptyLeaderBoard $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.EmptyLeaderBoardHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // org/amalgam/Service/GameServiceModule/GameService/verifyWord
       {
         try {
           String word = in.read_string ();
           this.verifyWord (word);
           out = $rh.createReply();
         } catch (org.amalgam.Service.GameExceptions.InvalidWordFormat $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.InvalidWordFormatHelper.write (out, $ex);
         } catch (org.amalgam.Service.GameExceptions.DuplicateWordException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.DuplicateWordExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // org/amalgam/Service/GameServiceModule/GameService/validateTotalPoints
       {
         try {
           String word[] = org.amalgam.Service.GameServiceModule.GameServicePackage.wordsHelper.read (in);
           int $result = (int)0;
           $result = this.validateTotalPoints (word);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (org.amalgam.Service.GameExceptions.InsufficientWordPoints $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.InsufficientWordPointsHelper.write (out, $ex);
         } catch (org.amalgam.Service.GameExceptions.InvalidTotalPoints $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.InvalidTotalPointsHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // org/amalgam/Service/GameServiceModule/GameService/fetchWinner
       {
         try {
           int lobbyId = in.read_long ();
           String $result = null;
           $result = this.fetchWinner (lobbyId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (org.amalgam.Service.GameExceptions.LobbyDoesNotExist $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.LobbyDoesNotExistHelper.write (out, $ex);
         } catch (org.amalgam.Service.GameExceptions.WinnerDoesNotExist $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.WinnerDoesNotExistHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // org/amalgam/Service/GameServiceModule/GameService/insertLobby
       {
         try {
           org.amalgam.Utils.Objects.Lobby lobby = org.amalgam.Service.GameServiceModule.GameServicePackage.LobbyHelper.read (in);
           this.insertLobby (lobby);
           out = $rh.createReply();
         } catch (org.amalgam.Service.GameExceptions.InvalidLobbyData $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Service.GameExceptions.InvalidLobbyDataHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/Service/GameServiceModule/GameService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameService _this() 
  {
    return GameServiceHelper.narrow(
    super._this_object());
  }

  public GameService _this(org.omg.CORBA.ORB orb) 
  {
    return GameServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameServicePOA
