package org.amalgam.Service.GameServiceModule;


/**
* org/amalgam/Service/GameServiceModule/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Wednesday, May 8, 2024 1:23:59 AM SGT
*/

public interface GameServiceOperations 
{
  org.amalgam.Utils.Objects.GameRoom matchMake (org.amalgam.Utils.UIControllers.PlayerCallback player_callback) throws org.amalgam.Utils.Exceptions.MatchCreationFailedException;
  char[][] fetchWordBox (int roomID) throws org.amalgam.Utils.Exceptions.WordFetchFailedException, org.amalgam.Utils.Exceptions.InvalidRoomIDException;
  org.amalgam.Utils.Objects.Leaderboard[] getLeaderboards () throws org.amalgam.Utils.Exceptions.EmptyLeaderBoardException;
  void verifyWord (String word) throws org.amalgam.Utils.Exceptions.InvalidWordFormatException, org.amalgam.Utils.Exceptions.DuplicateWordException;
  int validateTotalPoints (String[] word) throws org.amalgam.Utils.Exceptions.InsufficientWordPointsException, org.amalgam.Utils.Exceptions.InvalidTotalPointsException;
  String fetchWinner (int lobbyId) throws org.amalgam.Utils.Exceptions.LobbyDoesNotExistException, org.amalgam.Utils.Exceptions.WinnerDoesNotExistException;
} // interface GameServiceOperations
