package org.amalgam.Service.GameServiceModule;


/**
* org/amalgam/Service/GameServiceModule/PlayerCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:29:37 PM SGT
*/

public interface PlayerCallback extends PlayerCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallback
