# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.Service generated by omniidl

import omniORB
omniORB.updateModule("org.amalgam.Service")

# ** 1. Stub files contributing to this module
import GameService_idl
import PlayerService_idl

# ** 2. Sub-modules
from . import GameServiceModule
from . import PlayerServiceModule

# ** 3. End
