# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.Utils.Exceptions generated by omniidl

import omniORB
omniORB.updateModule("org.amalgam.Utils.Exceptions")

# ** 1. Stub files contributing to this module
import ProgramUtilities_idl

# ** 2. Sub-modules

# ** 3. End
