package org.amalgam.Service.Player;

/**
* org/amalgam/Service/Player/ControllerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Saturday, April 27, 2024 5:35:22 PM SGT
*/

public final class ControllerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.Player.ControllerInterface value = null;

  public ControllerInterfaceHolder ()
  {
  }

  public ControllerInterfaceHolder (org.amalgam.Service.Player.ControllerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.Player.ControllerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.Player.ControllerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.Player.ControllerInterfaceHelper.type ();
  }

}
