package org.amalgam.Service.Player;


/**
* org/amalgam/Service/Player/PlayerCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Monday, April 29, 2024 7:32:02 PM SGT
*/

public interface PlayerCallback extends PlayerCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallback
