# DO NOT EDIT THIS FILE!
#
# Python module org__POA generated by omniidl

import omniORB
omniORB.updateModule("org__POA")

# ** 1. Stub files contributing to this module
import GameService_idl
import PlayerService_idl
import ProgramUtilities_idl
import UIControllers_idl

# ** 2. Sub-modules
from . import amalgam

# ** 3. End
