package org.amalgam.DAL.DALLobby;


import org.amalgam.lexilogicserver.model.utilities.corbautils.LobbyImpl;

/**
* org/amalgam/DAL/DALLobby/LobbyDALOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public interface LobbyDALOperations 
{
  void insertNewLobby (int lobbyId, String createdBy, String winner) throws org.amalgam.DAL.SQLExceptions.SQLCreateError;
  LobbyImpl getLobbyByID (int lobbyId) throws org.amalgam.DAL.SQLExceptions.SQLRetrieveError;
} // interface LobbyDALOperations
