package org.amalgam.DAL.DALLobby;

/**
* org/amalgam/DAL/DALLobby/LobbyDALHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public final class LobbyDALHolder implements org.omg.CORBA.portable.Streamable
{
  public LobbyDAL value = null;

  public LobbyDALHolder ()
  {
  }

  public LobbyDALHolder (LobbyDAL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LobbyDALHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LobbyDALHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LobbyDALHelper.type ();
  }

}
