package org.amalgam.Service.Player;

/**
* org/amalgam/Service/Player/PlayerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Saturday, April 27, 2024 5:34:27 PM SGT
*/

public final class PlayerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.Player.PlayerService value = null;

  public PlayerServiceHolder ()
  {
  }

  public PlayerServiceHolder (org.amalgam.Service.Player.PlayerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.Player.PlayerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.Player.PlayerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.Player.PlayerServiceHelper.type ();
  }

}
