package org.amalgam.Service.Player;


/**
* org/amalgam/Service/Player/PlayerCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Saturday, April 27, 2024 5:34:27 PM SGT
*/

public interface PlayerCallbackOperations 
{
  void uiCall () throws org.amalgam.Service.PlayerExceptions.InvalidRequest;
  void setUser (org.amalgam.Service.Player.PlayerServicePackage.Player player) throws org.amalgam.Service.PlayerExceptions.InvalidRequest;
  org.amalgam.Service.Player.PlayerServicePackage.Player getPlayer () throws org.amalgam.Service.PlayerExceptions.InvalidRequest;
} // interface PlayerCallbackOperations
