# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam generated by omniidl

import omniORB
omniORB.updateModule("org__POA.amalgam")

# ** 1. Stub files contributing to this module
import GameService_idl
import PlayerService_idl
import ProgramUtilities_idl
import UIControllers_idl

# ** 2. Sub-modules
from . import Service
from . import Utils
from . import ControllerException
from . import UIControllers

# ** 3. End
