package org.amalgam.Utils.UIControllers;


/**
* org/amalgam/Utils/UIControllers/ControllerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 2:06:55 AM SGT
*/

public interface ControllerInterfaceOperations 
{
  void setObjectsUser (String objects) throws org.amalgam.Utils.Exceptions.InvalidRequestException;
  void fetchAndUpdate (String jsonFileName, org.omg.CORBA.Any dataType) throws org.amalgam.Utils.Exceptions.InvalidRequestException;
} // interface ControllerInterfaceOperations
