package org.amalgam.Utils.UIControllers;


/**
* org/amalgam/Utils/UIControllers/ControllerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 2:06:55 AM SGT
*/

public abstract class ControllerInterfacePOA extends org.omg.PortableServer.Servant
 implements org.amalgam.Utils.UIControllers.ControllerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setObjectsUser", new java.lang.Integer (0));
    _methods.put ("fetchAndUpdate", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/amalgam/Utils/UIControllers/ControllerInterface/setObjectsUser
       {
         try {
           String objects = in.read_string ();
           this.setObjectsUser (objects);
           out = $rh.createReply();
         } catch (org.amalgam.Utils.Exceptions.InvalidRequestException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.Exceptions.InvalidRequestExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // org/amalgam/Utils/UIControllers/ControllerInterface/fetchAndUpdate
       {
         try {
           String jsonFileName = in.read_string ();
           org.omg.CORBA.Any dataType = in.read_any ();
           this.fetchAndUpdate (jsonFileName, dataType);
           out = $rh.createReply();
         } catch (org.amalgam.Utils.Exceptions.InvalidRequestException $ex) {
           out = $rh.createExceptionReply ();
           org.amalgam.Utils.Exceptions.InvalidRequestExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/Utils/UIControllers/ControllerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ControllerInterface _this() 
  {
    return ControllerInterfaceHelper.narrow(
    super._this_object());
  }

  public ControllerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ControllerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ControllerInterfacePOA
