package org.amalgam.Service.GameServiceModule;

/**
* org/amalgam/Service/GameServiceModule/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 16, 2024 1:07:05 AM PST
*/

public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameServiceModule.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (org.amalgam.Service.GameServiceModule.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameServiceModule.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameServiceModule.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameServiceModule.GameServiceHelper.type ();
  }

}
