package org.amalgam.Service.PlayerServiceModule.PlayerServicePackage;


/**
* org/amalgam/Service/PlayerServiceModule/PlayerServicePackage/historyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Wednesday, May 8, 2024 1:24:15 AM SGT
*/

public final class historyHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Utils.Objects.Lobby value[] = null;

  public historyHolder ()
  {
  }

  public historyHolder (org.amalgam.Utils.Objects.Lobby[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = historyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    historyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return historyHelper.type ();
  }

}
