package org.amalgam.Service.Game;

/**
* org/amalgam/Service/Game/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.Game.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (org.amalgam.Service.Game.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.Game.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.Game.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.Game.GameServiceHelper.type ();
  }

}
