package org.amalgam.DAL.DALPlayer;


import org.amalgam.lexilogicserver.model.utilities.corbautils.PlayerImpl;

/**
* org/amalgam/DAL/DALPlayer/PlayerDALOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public interface PlayerDALOperations 
{
  void insertNewPlayer (String username, String password, String lastLogin) throws org.amalgam.DAL.SQLExceptions.SQLCreateError;
  PlayerImpl getPlayerByID (int playerID) throws org.amalgam.DAL.SQLExceptions.SQLRetrieveError;
  void updatePassword (int playerID, String newPassword) throws org.amalgam.DAL.SQLExceptions.SQLUpdateError;
  void updateUsername (int playerID, String newUsername) throws org.amalgam.DAL.SQLExceptions.SQLUpdateError;
  void deletePlayer (int playerID) throws org.amalgam.DAL.SQLExceptions.SQLDeleteError;
} // interface PlayerDALOperations
