package org.amalgam.ControllerException;

/**
* org/amalgam/ControllerException/InvalidRequestExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Thursday, May 16, 2024 1:07:10 AM PST
*/

public final class InvalidRequestExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.ControllerException.InvalidRequestException value = null;

  public InvalidRequestExceptionHolder ()
  {
  }

  public InvalidRequestExceptionHolder (org.amalgam.ControllerException.InvalidRequestException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.ControllerException.InvalidRequestExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.ControllerException.InvalidRequestExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.ControllerException.InvalidRequestExceptionHelper.type ();
  }

}
