package org.amalgam.DAL.DALLeaderBoard;


/**
* org/amalgam/DAL/DALLeaderBoard/_LeaderboardDALStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 5:44:43 PM SGT
*/

public class _LeaderboardDALStub extends org.omg.CORBA.portable.ObjectImpl implements org.amalgam.DAL.DALLeaderBoard.LeaderboardDAL
{

  public void insertNewLeaderboard (int userID, int totalPoints) throws org.amalgam.DAL.SQLExceptions.SQLCreateError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertNewLeaderboard", true);
                $out.write_long (userID);
                $out.write_long (totalPoints);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/DAL/SQLExceptions/SQLCreateError:1.0"))
                    throw org.amalgam.DAL.SQLExceptions.SQLCreateErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                insertNewLeaderboard (userID, totalPoints        );
            } finally {
                _releaseReply ($in);
            }
  } // insertNewLeaderboard

  public org.amalgam.DAL.DALLeaderBoard.LeaderboardDALPackage.Leaderboard getLeaderboardByID (int leaderboardID) throws org.amalgam.DAL.SQLExceptions.SQLRetrieveError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboardByID", true);
                $out.write_long (leaderboardID);
                $in = _invoke ($out);
                org.amalgam.DAL.DALLeaderBoard.LeaderboardDALPackage.Leaderboard $result = org.amalgam.DAL.DALLeaderBoard.LeaderboardDALPackage.LeaderboardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/DAL/SQLExceptions/SQLRetrieveError:1.0"))
                    throw org.amalgam.DAL.SQLExceptions.SQLRetrieveErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboardByID (leaderboardID        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboardByID

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/DAL/DALLeaderBoard/LeaderboardDAL:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "org.amalgam.DAL.DALLeaderBoard._LeaderboardDALStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LeaderboardDALStub
