package org.amalgam.DAL.DALLeaderBoard;


/**
* org/amalgam/DAL/DALLeaderBoard/LeaderboardDAL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 5:44:43 PM SGT
*/

public interface LeaderboardDAL extends LeaderboardDALOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LeaderboardDAL
