package org.amalgam.DAL.DALGameDetail;


/**
* org/amalgam/DAL/DALGameDetail/GameDetailsDAL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 5:44:19 PM SGT
*/

public interface GameDetailsDAL extends GameDetailsDALOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameDetailsDAL
