package org.amalgam.UIControllers;

/**
* org/amalgam/UIControllers/PlayerCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Wednesday, May 29, 2024 9:39:28 PM PST
*/

public final class PlayerCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerCallback value = null;

  public PlayerCallbackHolder ()
  {
  }

  public PlayerCallbackHolder (PlayerCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerCallbackHelper.type ();
  }

}
