package org.amalgam.UIControllers;


/**
* org/amalgam/UIControllers/PlayerCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UIControllers.idl
* Monday, July 1, 2024 10:33:07 PM SGT
*/

public interface PlayerCallback extends PlayerCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallback
