package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/DeleteAccountFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Monday, April 29, 2024 7:32:02 PM SGT
*/

public final class DeleteAccountFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public DeleteAccountFailed ()
  {
    super(DeleteAccountFailedHelper.id());
  } // ctor

  public DeleteAccountFailed (String _reason)
  {
    super(DeleteAccountFailedHelper.id());
    reason = _reason;
  } // ctor


  public DeleteAccountFailed (String $reason, String _reason)
  {
    super(DeleteAccountFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class DeleteAccountFailed
