package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/GameResultUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Saturday, April 27, 2024 5:35:22 PM SGT
*/

public final class GameResultUnavailable extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameResultUnavailable ()
  {
    super(GameResultUnavailableHelper.id());
  } // ctor

  public GameResultUnavailable (String _reason)
  {
    super(GameResultUnavailableHelper.id());
    reason = _reason;
  } // ctor


  public GameResultUnavailable (String $reason, String _reason)
  {
    super(GameResultUnavailableHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameResultUnavailable
