package org.amalgam.Service.PlayerExceptions;

/**
* org/amalgam/Service/PlayerExceptions/InvalidRequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Monday, April 29, 2024 7:32:02 PM SGT
*/

public final class InvalidRequestHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.PlayerExceptions.InvalidRequest value = null;

  public InvalidRequestHolder ()
  {
  }

  public InvalidRequestHolder (org.amalgam.Service.PlayerExceptions.InvalidRequest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.PlayerExceptions.InvalidRequestHelper.type ();
  }

}
