#include "objects/player/Player.idl"
#include "exceptions/InvalidRequestException.idl"
#include "exceptions/UserExistenceException.idl"

    module Client {

        interface Client {
            void uiCall()
            raises (InvalidRequestException)

            void setUser(in Player player)
            raises (InvalidRequestException)

            User getPlayer()
            raises (UserExistenceException)

        };

    };
