package org.amalgam.Service.GameServiceModule.GameServicePackage;


/**
* org/amalgam/Service/GameServiceModule/GameServicePackage/leaderboardsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:29:37 PM SGT
*/

public final class leaderboardsHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Utils.Objects.Leaderboard value[] = null;

  public leaderboardsHolder ()
  {
  }

  public leaderboardsHolder (org.amalgam.Utils.Objects.Leaderboard[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = leaderboardsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    leaderboardsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return leaderboardsHelper.type ();
  }

}
