package org.amalgam.Service.GameServiceModule;


/**
* org/amalgam/Service/GameServiceModule/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Sunday, 26 May 2024 00:11:51 o'clock PST
*/

public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
