package org.amalgam.lexilogicserver.DAL.DALLeaderBoard.LeaderboardDALPackage;


/**
* org/amalgam/lexilogicserver/DAL/DALLeaderBoard/LeaderboardDALPackage/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public int leaderboardID = (int)0;
  public int userID = (int)0;
  public int totalPoints = (int)0;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (int _leaderboardID, int _userID, int _totalPoints)
  {
    leaderboardID = _leaderboardID;
    userID = _userID;
    totalPoints = _totalPoints;
  } // ctor

} // class Leaderboard
