#include "exceptions/InvalidRequestException.idl"
#include "exceptions/NotLoggedInException.idl"
#include "exceptions/ObjectExistenceException.idl"
#include "objects/Char.idl"
#include "objects/GameDetails.idl"
#include "objects/Lobby.idl"
#include "Client.idl"

module requests {

interface GameRequest {

    Room matchMake(Client client)
    raises (InvalidRequestException, NotLoggedInException, ObjectExistenceException);

    sequence < sequence < Char > > fetchWordbox(int roomid)
    raises (InvalidRequestException);

    void verifyWord(string word)
    raises (InvalidRequestException);

    sequence <string> fetchLeaderBoard()
    raises (InvalidRequestException, NotLoggedInException, ObjectExistenceException);

    int validateTotalPts(sequence <string> words)
    raises (InvalidRequestException);

    string fetchWinner()
    raises (InvalidRequestException);

    void saveToDb(Lobby game)
    raises (InvalidRequestException);

};

};
