#include "exceptions/InvalidCredentialsException.idl"
#include "exceptions/AlreadyLoggedInException.idl"
#include "exceptions/NotLoggedInException.idl"
#include "exceptions/UserExistenceException.idl"
#include "exceptions/InvalidRequestException.idl"
#include "exceptions/InvalidWordException.idl"
#include "exceptions/ObjectExistenceException.idl"
#include "exceptions/NoPlayersAvailableException.idl"
#include "objects/game/GameDetail.idl"
#include "objects/game/Lobby.idl"
#include "objects/game/Player.idl"
#include "Client.idl"

module requests {

interface UserRequest {

    void login(Client client)
    raises (InvalidCredentialsException, AlreadyLoggedInException, UserExistenceException);

    void logout()
    raises (NotLoggedInException);

    void changeUsername (in string username, in string newUsername)
    raises (InvalidRequestException,UserExistenceException, NotLoggedInException, ObjectExistenceException);

    void changePassword(in string username, in string newPassword)
    raises (InvalidRequestException,UserExistenceException, NotLoggedInException, ObjectExistenceException);

    void deleteProfile (in string username)
    raises(InvalidRequestException,NotLoggedInException,ObjectExistenceException)

    void startGame()
    raises (NoPlayersAvailableException, NotLoggedInException);

    void submitWord(in string word)
    raises (InvalidWordException, NotLoggedInException);

    void getGameResult()
    raises (NotLoggedInException);

    void getGameHistory()
    raises (NotLoggedInException, InvalidRequestException);

    sequence<LeaderBoard> getLeaderboard()
    raises (NotLoggedInException);

};

};
