package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/WordFetchExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:35:13 PM SGT
*/

public final class WordFetchExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameExceptions.WordFetchException value = null;

  public WordFetchExceptionHolder ()
  {
  }

  public WordFetchExceptionHolder (org.amalgam.Service.GameExceptions.WordFetchException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameExceptions.WordFetchExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameExceptions.WordFetchExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameExceptions.WordFetchExceptionHelper.type ();
  }

}
