package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/leaderboardsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:34:25 PM SGT
*/

abstract public class leaderboardsHelper
{
  private static String  _id = "IDL:org/amalgam/Service/Game/GameService/leaderboards:1.0";

  public static void insert (org.omg.CORBA.Any a, org.amalgam.Service.Game.GameServicePackage.Leaderboard[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.amalgam.Service.Game.GameServicePackage.Leaderboard[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.amalgam.Service.Game.GameServicePackage.LeaderboardHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.amalgam.Service.Game.GameServicePackage.leaderboardsHelper.id (), "leaderboards", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.amalgam.Service.Game.GameServicePackage.Leaderboard[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.amalgam.Service.Game.GameServicePackage.Leaderboard value[] = null;
    int _len0 = istream.read_long ();
    value = new org.amalgam.Service.Game.GameServicePackage.Leaderboard[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.amalgam.Service.Game.GameServicePackage.LeaderboardHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.amalgam.Service.Game.GameServicePackage.Leaderboard[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.amalgam.Service.Game.GameServicePackage.LeaderboardHelper.write (ostream, value[_i0]);
  }

}
