package org.amalgam.Service.Game.GameServicePackage;


/**
* org/amalgam/Service/Game/GameServicePackage/Lobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:34:25 PM SGT
*/

public final class Lobby implements org.omg.CORBA.portable.IDLEntity
{
  public int lobbyId = (int)0;
  public String created_by = null;
  public String winner = null;

  public Lobby ()
  {
  } // ctor

  public Lobby (int _lobbyId, String _created_by, String _winner)
  {
    lobbyId = _lobbyId;
    created_by = _created_by;
    winner = _winner;
  } // ctor

  public int getLobbyId() {
    return lobbyId;
  }

  public void setLobbyId(int lobbyId) {
    this.lobbyId = lobbyId;
  }

  public String getCreated_by() {
    return created_by;
  }

  public void setCreated_by(String created_by) {
    this.created_by = created_by;
  }

  public String getWinner() {
    return winner;
  }

  public void setWinner(String winner) {
    this.winner = winner;
  }
} // class Lobby
