package org.amalgam.Utils.Exceptions;

/**
* org/amalgam/Utils/Exceptions/AccountCreationFailedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 29, 2024 9:39:28 PM PST
*/

public final class AccountCreationFailedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AccountCreationFailedException value = null;

  public AccountCreationFailedExceptionHolder ()
  {
  }

  public AccountCreationFailedExceptionHolder (AccountCreationFailedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountCreationFailedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountCreationFailedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountCreationFailedExceptionHelper.type ();
  }

}
