package org.amalgam.Utils.Exceptions;


/**
* org/amalgam/Utils/Exceptions/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 29, 2024 9:39:28 PM PST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor

  public AlreadyLoggedInException (String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id());
    message = _message;
  } // ctor


  public AlreadyLoggedInException (String $reason, String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class AlreadyLoggedInException
