package org.amalgam.Utils.Exceptions;

/**
* org/amalgam/Utils/Exceptions/ChangeUsernameFailedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Sunday, 26 May 2024 00:11:52 o'clock PST
*/

public final class ChangeUsernameFailedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ChangeUsernameFailedException value = null;

  public ChangeUsernameFailedExceptionHolder ()
  {
  }

  public ChangeUsernameFailedExceptionHolder (ChangeUsernameFailedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChangeUsernameFailedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChangeUsernameFailedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChangeUsernameFailedExceptionHelper.type ();
  }

}
