package org.amalgam.Utils.Exceptions;

/**
* org/amalgam/Utils/Exceptions/LobbyDoesNotExistExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 29, 2024 9:39:28 PM PST
*/

public final class LobbyDoesNotExistExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public LobbyDoesNotExistException value = null;

  public LobbyDoesNotExistExceptionHolder ()
  {
  }

  public LobbyDoesNotExistExceptionHolder (LobbyDoesNotExistException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LobbyDoesNotExistExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LobbyDoesNotExistExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LobbyDoesNotExistExceptionHelper.type ();
  }

}
