package org.amalgam.Utils.Exceptions;


/**
* org/amalgam/Utils/Exceptions/UpdateLastLoginException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Sunday, 26 May 2024 00:11:52 o'clock PST
*/

public final class UpdateLastLoginException extends org.omg.CORBA.UserException
{
  public String message = null;

  public UpdateLastLoginException ()
  {
    super(UpdateLastLoginExceptionHelper.id());
  } // ctor

  public UpdateLastLoginException (String _message)
  {
    super(UpdateLastLoginExceptionHelper.id());
    message = _message;
  } // ctor


  public UpdateLastLoginException (String $reason, String _message)
  {
    super(UpdateLastLoginExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UpdateLastLoginException
