package org.amalgam.lexilogicserver.DAL.DALLobby.LobbyDALPackage;


/**
* org/amalgam/lexilogicserver/DAL/DALLobby/LobbyDALPackage/Lobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Saturday, April 27, 2024 12:17:01 AM SGT
*/

public final class Lobby implements org.omg.CORBA.portable.IDLEntity
{
  public String lobbyId = null;
  public String createdBy = null;
  public String winner = null;

  public Lobby ()
  {
  } // ctor

  public Lobby (String _lobbyId, String _createdBy, String _winner)
  {
    lobbyId = _lobbyId;
    createdBy = _createdBy;
    winner = _winner;
  } // ctor

} // class Lobby
