package org.amalgam.Service.Player;


/**
* org/amalgam/Service/Player/ControllerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Thursday, May 2, 2024 9:20:59 AM CST
*/

public interface ControllerInterfaceOperations 
{
  void setObjectsUser (String objects) throws org.amalgam.Service.PlayerExceptions.InvalidRequest, org.amalgam.Service.PlayerExceptions.UserExistenceException;
  void fetchAndUpdate () throws org.amalgam.Service.PlayerExceptions.InvalidRequest;
} // interface ControllerInterfaceOperations
