package org.amalgam.Utils.ObjectExceptions;


/**
* org/amalgam/Utils/ObjectExceptions/CloseLobbyException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:32:16 PM SGT
*/

public final class CloseLobbyException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public CloseLobbyException ()
  {
    super(CloseLobbyExceptionHelper.id());
  } // ctor

  public CloseLobbyException (String _reason)
  {
    super(CloseLobbyExceptionHelper.id());
    reason = _reason;
  } // ctor


  public CloseLobbyException (String $reason, String _reason)
  {
    super(CloseLobbyExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class CloseLobbyException
