package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameDetailHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 12:45:43 AM SGT
*/

abstract public class GameDetailHelper
{
  private static String  _id = "IDL:org/amalgam/Utils/Objects/GameDetail:1.0";

  public static void insert (org.omg.CORBA.Any a, GameDetail that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameDetail extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameDetailHelper.id (), "GameDetail");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameDetail read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameDetailStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameDetail value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameDetail narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameDetail)
      return (GameDetail)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameDetailStub stub = new _GameDetailStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameDetail unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameDetail)
      return (GameDetail)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameDetailStub stub = new _GameDetailStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
