package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameDetailOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 12:45:43 AM SGT
*/

public interface GameDetailOperations 
{
  int playerID ();
  void playerID (int newPlayerID);
  int lobbyID ();
  void lobbyID (int newLobbyID);
  int totalPoints ();
  void totalPoints (int newTotalPoints);
  void updateTotalPoints (int newPoints) throws org.amalgam.Utils.Exceptions.InvalidPointsException, org.amalgam.Utils.Exceptions.SQLError;
  int getPlayerID () throws org.amalgam.Utils.Exceptions.PlayerDoesNotExistException;
  int getLobbyID () throws org.amalgam.Utils.Exceptions.LobbyDoesNotExistException;
} // interface GameDetailOperations
