package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramUtilities.idl
* Wednesday, May 8, 2024 12:45:43 AM SGT
*/

public interface Leaderboard extends LeaderboardOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Leaderboard
