package org.amalgam.DAL.DALLobby;


/**
* org/amalgam/DAL/DALLobby/LobbyDAL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataAccessLayer.idl
* Sunday, May 5, 2024 5:01:36 PM SGT
*/

public interface LobbyDAL extends LobbyDALOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LobbyDAL
