package org.amalgam.Service.PlayerServiceModule;


import org.amalgam.lexilogicserver.model.utilities.corbautils.PlayerImpl;

/**
* org/amalgam/Service/PlayerServiceModule/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Wednesday, May 8, 2024 12:45:30 AM SGT
*/

public interface PlayerServiceOperations 
{
  void login (org.amalgam.Utils.UIControllers.PlayerCallback player_callback) throws org.amalgam.Utils.Exceptions.AlreadyLoggedInException, org.amalgam.Utils.Exceptions.InvalidCredentialsException, org.amalgam.Utils.Exceptions.UserExistenceException;
  void logout () throws org.amalgam.Utils.Exceptions.NotLoggedInException;
  void createAccount (PlayerImpl newPlayer) throws org.amalgam.Utils.Exceptions.AccountCreationFailedException;
  void changeUsername (String username, String newUsername) throws org.amalgam.Utils.Exceptions.ChangeUsernameFailedException;
  void changePassword (String username, String newPassword) throws org.amalgam.Utils.Exceptions.ChangePasswordFailedException;
  void accountDeletionRequest (String username) throws org.amalgam.Utils.Exceptions.DeleteAccountFailedException;
  String getGameResult (String playerName) throws org.amalgam.Utils.Exceptions.GameResultUnavailableException, org.amalgam.Utils.Exceptions.InGameException;
  org.amalgam.Utils.Objects.Lobby[] getGameHistory (String playerName) throws org.amalgam.Utils.Exceptions.GameHistoryUnavailableException, org.amalgam.Utils.Exceptions.InGameException;
} // interface PlayerServiceOperations
