package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/AccountCreationFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Sunday, May 5, 2024 3:44:39 PM SGT
*/

public final class AccountCreationFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public AccountCreationFailed ()
  {
    super(AccountCreationFailedHelper.id());
  } // ctor

  public AccountCreationFailed (String _reason)
  {
    super(AccountCreationFailedHelper.id());
    reason = _reason;
  } // ctor


  public AccountCreationFailed (String $reason, String _reason)
  {
    super(AccountCreationFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class AccountCreationFailed
