package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/ChangeUsernameFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class ChangeUsernameFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ChangeUsernameFailed ()
  {
    super(ChangeUsernameFailedHelper.id());
  } // ctor

  public ChangeUsernameFailed (String _reason)
  {
    super(ChangeUsernameFailedHelper.id());
    reason = _reason;
  } // ctor


  public ChangeUsernameFailed (String $reason, String _reason)
  {
    super(ChangeUsernameFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ChangeUsernameFailed
