package org.amalgam.Service.PlayerExceptions;

/**
* org/amalgam/Service/PlayerExceptions/ChangeUsernameFailedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class ChangeUsernameFailedHolder implements org.omg.CORBA.portable.Streamable
{
  public ChangeUsernameFailed value = null;

  public ChangeUsernameFailedHolder ()
  {
  }

  public ChangeUsernameFailedHolder (ChangeUsernameFailed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChangeUsernameFailedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChangeUsernameFailedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChangeUsernameFailedHelper.type ();
  }

}
