package org.amalgam.Service.PlayerExceptions;

/**
* org/amalgam/Service/PlayerExceptions/GameResultUnavailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class GameResultUnavailableHolder implements org.omg.CORBA.portable.Streamable
{
  public GameResultUnavailable value = null;

  public GameResultUnavailableHolder ()
  {
  }

  public GameResultUnavailableHolder (GameResultUnavailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameResultUnavailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameResultUnavailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameResultUnavailableHelper.type ();
  }

}
