package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/MatchCreationFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class MatchCreationFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public MatchCreationFailed ()
  {
    super(MatchCreationFailedHelper.id());
  } // ctor

  public MatchCreationFailed (String _reason)
  {
    super(MatchCreationFailedHelper.id());
    reason = _reason;
  } // ctor


  public MatchCreationFailed (String $reason, String _reason)
  {
    super(MatchCreationFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class MatchCreationFailed
