package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/ObjectExistence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class ObjectExistence extends org.omg.CORBA.UserException
{
  public String message = null;

  public ObjectExistence ()
  {
    super(ObjectExistenceHelper.id());
  } // ctor

  public ObjectExistence (String _message)
  {
    super(ObjectExistenceHelper.id());
    message = _message;
  } // ctor


  public ObjectExistence (String $reason, String _message)
  {
    super(ObjectExistenceHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ObjectExistence
