package org.amalgam.Service.PlayerExceptions;

/**
* org/amalgam/Service/PlayerExceptions/StartGameFailedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Friday, May 3, 2024 11:29:23 PM SGT
*/

public final class StartGameFailedHolder implements org.omg.CORBA.portable.Streamable
{
  public StartGameFailed value = null;

  public StartGameFailedHolder ()
  {
  }

  public StartGameFailedHolder (StartGameFailed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StartGameFailedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StartGameFailedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StartGameFailedHelper.type ();
  }

}
