package org.amalgam.Service.GameServiceModule;


/**
* org/amalgam/Service/GameServiceModule/PlayerCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Friday, May 3, 2024 11:33:52 PM SGT
*/

public interface PlayerCallbackOperations 
{
  void uiCall (int lobbyId) throws org.amalgam.Service.GameExceptions.InvalidRequestException;
  void setUser (org.amalgam.Utils.Objects.Player player, int lobbyId) throws org.amalgam.Service.GameExceptions.InvalidRequestException;
  org.amalgam.Utils.Objects.Player getPlayer (int lobbyId) throws org.amalgam.Service.GameExceptions.InvalidRequestException;
} // interface PlayerCallbackOperations
