package org.amalgam.Service.Game;


/**
* org/amalgam/Service/Game/PlayerCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, April 27, 2024 5:35:13 PM SGT
*/

public interface PlayerCallbackOperations 
{
  void uiCall () throws org.amalgam.Service.GameExceptions.InvalidRequestException;
  void setUser (org.amalgam.Service.Game.GameServicePackage.Player player) throws org.amalgam.Service.GameExceptions.InvalidRequestException;
  org.amalgam.Service.Game.GameServicePackage.Player getPlayer () throws org.amalgam.Service.GameExceptions.InvalidRequestException;
} // interface PlayerCallbackOperations
