package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/ChangePasswordFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Thursday, May 2, 2024 9:20:59 AM CST
*/

public final class ChangePasswordFailed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ChangePasswordFailed ()
  {
    super(ChangePasswordFailedHelper.id());
  } // ctor

  public ChangePasswordFailed (String _reason)
  {
    super(ChangePasswordFailedHelper.id());
    reason = _reason;
  } // ctor


  public ChangePasswordFailed (String $reason, String _reason)
  {
    super(ChangePasswordFailedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ChangePasswordFailed
