package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/InGameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Thursday, May 2, 2024 9:20:59 AM CST
*/

public final class InGameException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InGameException ()
  {
    super(InGameExceptionHelper.id());
  } // ctor

  public InGameException (String _reason)
  {
    super(InGameExceptionHelper.id());
    reason = _reason;
  } // ctor


  public InGameException (String $reason, String _reason)
  {
    super(InGameExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InGameException
