package org.amalgam.Service.PlayerExceptions;


/**
* org/amalgam/Service/PlayerExceptions/UserExistenceException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerService.idl
* Thursday, May 2, 2024 9:20:59 AM CST
*/

public final class UserExistenceException extends org.omg.CORBA.UserException
{
  public String message = null;

  public UserExistenceException ()
  {
    super(UserExistenceExceptionHelper.id());
  } // ctor

  public UserExistenceException (String _message)
  {
    super(UserExistenceExceptionHelper.id());
    message = _message;
  } // ctor


  public UserExistenceException (String $reason, String _message)
  {
    super(UserExistenceExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UserExistenceException
