package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/_LobbyStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public class _LobbyStub extends org.omg.CORBA.portable.ObjectImpl implements Lobby
{

  public int lobbyID ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_lobbyID", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return lobbyID (        );
            } finally {
                _releaseReply ($in);
            }
  } // lobbyID

  public void lobbyID (int newLobbyID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_lobbyID", true);
                $out.write_long (newLobbyID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                lobbyID (newLobbyID        );
            } finally {
                _releaseReply ($in);
            }
  } // lobbyID

  public String createdBy ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_createdBy", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createdBy (        );
            } finally {
                _releaseReply ($in);
            }
  } // createdBy

  public void createdBy (String newCreatedBy)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_createdBy", true);
                $out.write_string (newCreatedBy);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createdBy (newCreatedBy        );
            } finally {
                _releaseReply ($in);
            }
  } // createdBy

  public String winner ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_winner", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return winner (        );
            } finally {
                _releaseReply ($in);
            }
  } // winner

  public void winner (String newWinner)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_winner", true);
                $out.write_string (newWinner);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                winner (newWinner        );
            } finally {
                _releaseReply ($in);
            }
  } // winner

  public void updateWinner (String winnerName) throws org.amalgam.Utils.ObjectExceptions.InvalidNameException, org.amalgam.Utils.ObjectExceptions.PlayerDoesNotExistException, org.amalgam.Utils.ObjectExceptions.SQLError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateWinner", true);
                $out.write_string (winnerName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/InvalidNameException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.InvalidNameExceptionHelper.read ($in);
                else if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/PlayerDoesNotExistException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.PlayerDoesNotExistExceptionHelper.read ($in);
                else if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/SQLError:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.SQLErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateWinner (winnerName        );
            } finally {
                _releaseReply ($in);
            }
  } // updateWinner

  public void closeLobby () throws org.amalgam.Utils.ObjectExceptions.LobbyDoesNotExistException, org.amalgam.Utils.ObjectExceptions.CloseLobbyException, org.amalgam.Utils.ObjectExceptions.SQLError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("closeLobby", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/LobbyDoesNotExistException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.LobbyDoesNotExistExceptionHelper.read ($in);
                else if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/CloseLobbyException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.CloseLobbyExceptionHelper.read ($in);
                else if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/SQLError:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.SQLErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                closeLobby (        );
            } finally {
                _releaseReply ($in);
            }
  } // closeLobby

  public int getLobbyID () throws org.amalgam.Utils.ObjectExceptions.LobbyIDRetrievalException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLobbyID", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/LobbyIDRetrievalException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.LobbyIDRetrievalExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLobbyID (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLobbyID

  public String getCreatedBy () throws org.amalgam.Utils.ObjectExceptions.CreatedByRetrievalException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCreatedBy", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:org/amalgam/Utils/ObjectExceptions/CreatedByRetrievalException:1.0"))
                    throw org.amalgam.Utils.ObjectExceptions.CreatedByRetrievalExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCreatedBy (        );
            } finally {
                _releaseReply ($in);
            }
  } // getCreatedBy

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/amalgam/Utils/Objects/Lobby:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "org.amalgam.Utils.Objects._LobbyStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LobbyStub
