package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameDetailOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public interface GameDetailOperations 
{
  int playerID ();
  void playerID (int newPlayerID);
  int lobbyID ();
  void lobbyID (int newLobbyID);
  int totalPoints ();
  void totalPoints (int newTotalPoints);
  void updateTotalPoints (int newPoints) throws org.amalgam.Utils.ObjectExceptions.InvalidPointsException, org.amalgam.Utils.ObjectExceptions.SQLError;
  int getPlayerID () throws org.amalgam.Utils.ObjectExceptions.PlayerDoesNotExistException;
  int getLobbyID () throws org.amalgam.Utils.ObjectExceptions.LobbyDoesNotExistException;
} // interface GameDetailOperations
