package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/GameDetail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public interface GameDetail extends GameDetailOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameDetail
