package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/LeaderboardOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public interface LeaderboardOperations 
{
  int leaderboardID ();
  void leaderboardID (int newLeaderboardID);
  int playerID ();
  void playerID (int newPlayerID);
  int totalPoints ();
  void totalPoints (int newTotalPoints);
  void updateTotalPoints (int newPoints) throws org.amalgam.Utils.ObjectExceptions.InvalidPointsException, org.amalgam.Utils.ObjectExceptions.SQLError;
  int getPlayerID () throws org.amalgam.Utils.ObjectExceptions.PlayerDoesNotExistException;
  int getLeaderboardID () throws org.amalgam.Utils.ObjectExceptions.LeaderboardIDRetrievalException;
} // interface LeaderboardOperations
