package org.amalgam.Utils.Objects;


/**
* org/amalgam/Utils/Objects/LobbyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProgramObjects.idl
* Friday, May 3, 2024 11:33:44 PM SGT
*/

public interface LobbyOperations 
{
  int lobbyID ();
  void lobbyID (int newLobbyID);
  String createdBy ();
  void createdBy (String newCreatedBy);
  String winner ();
  void winner (String newWinner);
  void updateWinner (String winnerName) throws org.amalgam.Utils.ObjectExceptions.InvalidNameException, org.amalgam.Utils.ObjectExceptions.PlayerDoesNotExistException, org.amalgam.Utils.ObjectExceptions.SQLError;
  void closeLobby () throws org.amalgam.Utils.ObjectExceptions.LobbyDoesNotExistException, org.amalgam.Utils.ObjectExceptions.CloseLobbyException, org.amalgam.Utils.ObjectExceptions.SQLError;
  int getLobbyID () throws org.amalgam.Utils.ObjectExceptions.LobbyIDRetrievalException;
  String getCreatedBy () throws org.amalgam.Utils.ObjectExceptions.CreatedByRetrievalException;
} // interface LobbyOperations
