package org.amalgam.Service.GameExceptions;


/**
* org/amalgam/Service/GameExceptions/InsufficientWordPoints.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class InsufficientWordPoints extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InsufficientWordPoints ()
  {
    super(InsufficientWordPointsHelper.id());
  } // ctor

  public InsufficientWordPoints (String _reason)
  {
    super(InsufficientWordPointsHelper.id());
    reason = _reason;
  } // ctor


  public InsufficientWordPoints (String $reason, String _reason)
  {
    super(InsufficientWordPointsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InsufficientWordPoints
