package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/InvalidLobbyDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class InvalidLobbyDataHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameExceptions.InvalidLobbyData value = null;

  public InvalidLobbyDataHolder ()
  {
  }

  public InvalidLobbyDataHolder (org.amalgam.Service.GameExceptions.InvalidLobbyData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameExceptions.InvalidLobbyDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameExceptions.InvalidLobbyDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameExceptions.InvalidLobbyDataHelper.type ();
  }

}
