package org.amalgam.Service.GameExceptions;

/**
* org/amalgam/Service/GameExceptions/MatchCreationFailedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class MatchCreationFailedHolder implements org.omg.CORBA.portable.Streamable
{
  public org.amalgam.Service.GameExceptions.MatchCreationFailed value = null;

  public MatchCreationFailedHolder ()
  {
  }

  public MatchCreationFailedHolder (org.amalgam.Service.GameExceptions.MatchCreationFailed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.amalgam.Service.GameExceptions.MatchCreationFailedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.amalgam.Service.GameExceptions.MatchCreationFailedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.amalgam.Service.GameExceptions.MatchCreationFailedHelper.type ();
  }

}
