package org.amalgam.Service.GameExceptions;


/**
* org/amalgam/Service/GameExceptions/WinnerDoesNotExist.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 2, 2024 9:20:49 AM CST
*/

public final class WinnerDoesNotExist extends org.omg.CORBA.UserException
{
  public String reason = null;

  public WinnerDoesNotExist ()
  {
    super(WinnerDoesNotExistHelper.id());
  } // ctor

  public WinnerDoesNotExist (String _reason)
  {
    super(WinnerDoesNotExistHelper.id());
    reason = _reason;
  } // ctor


  public WinnerDoesNotExist (String $reason, String _reason)
  {
    super(WinnerDoesNotExistHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class WinnerDoesNotExist
